name: Build and Release FLOW Antora UI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Install Gulp CLI
        run: npm install --global gulp-cli

      - name: Run Gulp tasks
        run: gulp default

      - name: Create UI zip
        run: |
          cd build
          zip -r ../flow-antora-ui.zip .
          cd ..

      - name: Read Version from package.json
        id: package-version
        run: |
          VERSION=$(jq -r '.version // "1.0.0"' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version extracted: $VERSION"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: "FLOW Antora UI v${{ env.VERSION }}"
          tag_name: "v${{ env.VERSION }}"
          token: ${{ secrets.GH_PAT }}
          files: flow-antora-ui.zip
